# Render deployment configuration

services:
  # Backend API service
  - type: web
    name: my-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free  # Changed to free tier
    region: ohio
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: NODE_ENV
        value: production
    autoDeploy: true

  # Frontend service
  - type: web
    name: my-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: free  # Changed to free tier
    region: ohio
    buildFilter:
      paths:
        - frontend/**
    envVars:
      - key: API_URL
        value: https://my-api.onrender.com
    autoDeploy: true

# Database configuration
databases:
  - name: db
    plan: free
    databaseName: my_database_name
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all